import {
  describe,
  it,
  expect,
  beforeAll,
  afterAll,
  beforeEach,
  afterEach,
  vi,
} from 'vitest';
import request from 'supertest';
import mongoose from 'mongoose';
import chalk from 'chalk';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import app from '../../../../app';
import { LegalPage } from '../legal.model';
import { ILegalPage } from '../legal.interface';
import { User } from '../../user/user.model';
import { USER_ROLES, COMPANY_ROLE } from '../../../../enums/user';
import { jwtHelper } from '../../../../helpers/jwtHelper';
import config from '../../../../config';
import { StatusCodes } from 'http-status-codes';
import { logApi } from '../../../../helpers/__tests__/testLogger';

chalk.level = 3;

vi.setConfig({ testTimeout: 30000 });

const bdd = {
  header: (text: string) => chalk.bold.cyan(text),
  section: (text: string) => chalk.bold.yellow(text),
  label: (text: string) => chalk.bold.hex('#38BDF8')(text),
  method: (m: 'GET' | 'POST' | 'PATCH' | 'DELETE' | 'PUT') => {
    switch (m) {
      case 'GET':
        return chalk.bold.green(m);
      case 'POST':
        return chalk.bold.yellow(m);
      case 'PATCH':
        return chalk.bold.magenta(m);
      case 'DELETE':
        return chalk.bold.red(m);
      default:
        return chalk.bold.blue(m);
    }
  },
  endpoint: (url: string) => chalk.bold.white(url),
  access: (role: string) => chalk.bold.hex('#F472B6')(role),
  keyword: (k: string) => chalk.bold.greenBright(k),
  scenario: (text: string) => chalk.bold.hex('#A855F7')(text),
  field: (name: string) => chalk.bold.hex('#F59E0B')(name),
};

let replSet: MongoMemoryReplSet;
let adminAccessToken: string;
let userAccessToken: string;

const assertSuccessResponse = (body: any) => {
  expect(body).toHaveProperty('success', true);
  expect(body).toHaveProperty('message');
};

const createTestUserAndToken = async (
  role: string,
  companyRole: string,
  email: string,
) => {
  const userId = new mongoose.Types.ObjectId().toString();
  await User.create({
    _id: userId,
    name: `${role} User`,
    email,
    password: 'Password123!',
    phone: `+${Math.floor(1000000000 + Math.random() * 9000000000)}`,
    role,
    companyRole,
    accountState: 'VERIFIED',
  });

  const token = jwtHelper.createToken(
    { id: userId, userId, role, email },
    config.jwt.jwt_secret as string,
    '1h',
  );
  return { userId, token };
};

const createLegalPageFixture = async (
  overrides: Partial<ILegalPage> = {},
) => {
  return LegalPage.create({
    title: `Legal Document ${new mongoose.Types.ObjectId()}`,
    content: '<p>Standard legal terms content...</p>',
    ...overrides,
  });
};

beforeAll(async () => {
  replSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } });
  await mongoose.connect(replSet.getUri());

  await User.deleteMany({});
  await LegalPage.deleteMany({});

  const adminData = await createTestUserAndToken(
    USER_ROLES.ADMIN,
    COMPANY_ROLE.OWNER,
    'admin-legal@test.com',
  );
  adminAccessToken = adminData.token;

  const userData = await createTestUserAndToken(
    USER_ROLES.USER,
    COMPANY_ROLE.CHAUFFEUR,
    'user-legal@test.com',
  );
  userAccessToken = userData.token;
});

afterAll(async () => {
  await mongoose.disconnect();
  await replSet.stop();
});

describe('Legal Module E2E Tests - Happy Paths & Business Workflows', () => {
  beforeEach(async () => {
    await LegalPage.deleteMany({});
  });

  afterEach(async () => {
    await LegalPage.deleteMany({});
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // 1. CREATE LEGAL PAGE
  // ═══════════════════════════════════════════════════════════════════════════
  describe('BDD-01 CREATE LEGAL PAGE (Happy Paths)', () => {
    it('BDD-01-A admin successfully creates a Terms of Service legal page', async () => {
      console.info(`
${bdd.header('📝 USER STORY:')}
As an Administrator
I want to create a new legal policy document (Terms of Service)
So that platform users have clear legal agreements and operating guidelines

${bdd.section('📋 BUSINESS RULES & QUERY PAYLOAD SPECIFICATIONS:')}
${bdd.label('• Primary Endpoint:')} ${bdd.method('POST')} ${bdd.endpoint('/api/v1/legals')}
${bdd.label('• Access:')} ${bdd.access('ADMIN Only')}
${bdd.label('• Mandatory Fields & Validation Rationale:')}
  - ${bdd.field('title')} (string): Unique policy name (e.g., 'Terms of Service', 'Privacy Policy').
  - ${bdd.field('content')} (string | optional): HTML or markdown formatted policy text.
${bdd.label('• Response Structure & Architectural Rationale:')}
  - { success: true, statusCode: 201, message: "Legal page created successfully", data: { _id, title, content, createdAt, updatedAt } }
  - ${bdd.field('_id')} (ObjectId): Unique legal page ID generated by MongoDB for lookups and admin updates.
  - ${bdd.field('title')} (string): Stored document headline displayed across web and mobile legal screens.
  - ${bdd.field('content')} (string): Rich content body rendered on the platform legal screens.
  - ${bdd.field('createdAt / updatedAt')} (ISO Date): Audit timestamps tracking document lifecycle.

${bdd.scenario('📖 BDD SCENARIO: Stage 1.1 — Create New Legal Policy')}
Feature: Legal Policy Creation

${bdd.keyword('Given')} an authenticated administrator
${bdd.keyword('When')} I POST /api/v1/legals with valid title and content
${bdd.keyword('Then')} I receive HTTP 201 Created with the persisted legal page record
${bdd.keyword('And')} the document is saved and accessible in the database
`);

      const payload = {
        title: 'Terms of Service',
        content: '<h1>Terms of Service</h1><p>Welcome to our platform. By using our service, you agree to these terms.</p>',
      };

      const response = await request(app)
        .post('/api/v1/legals')
        .set('Authorization', `Bearer ${adminAccessToken}`)
        .send(payload)
        .expect(StatusCodes.CREATED);

      logApi(
        'POST',
        '/api/v1/legals',
        { body: payload },
        response.body,
        'BDD-01-CREATE-LEGAL',
        'Admin creates Terms of Service legal page',
      );

      assertSuccessResponse(response.body);
      expect(response.body.data.title).toBe('Terms of Service');
      expect(response.body.data.content).toBe(payload.content);
      expect(response.body.data._id).toBeDefined();

      const saved = await LegalPage.findById(response.body.data._id);
      expect(saved).not.toBeNull();
      expect(saved?.title).toBe('Terms of Service');
    });

    it('BDD-01-B admin successfully creates a Privacy Policy without optional content', async () => {
      const payload = {
        title: 'Privacy Policy',
      };

      const response = await request(app)
        .post('/api/v1/legals')
        .set('Authorization', `Bearer ${adminAccessToken}`)
        .send(payload)
        .expect(StatusCodes.CREATED);

      assertSuccessResponse(response.body);
      expect(response.body.data.title).toBe('Privacy Policy');
      expect(response.body.data.content).toBe('');
      expect(response.body.data._id).toBeDefined();
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. GET ALL LEGAL PAGES
  // ═══════════════════════════════════════════════════════════════════════════
  describe('BDD-02 GET ALL LEGAL PAGES (Public / Browsing)', () => {
    it('BDD-02 public users can retrieve all published legal pages', async () => {
      console.info(`
${bdd.header('📝 USER STORY:')}
As any Platform User or Visitor
I want to fetch all available legal pages
So that I can choose which policy to review

${bdd.section('📋 BUSINESS RULES & QUERY PAYLOAD SPECIFICATIONS:')}
${bdd.label('• Primary Endpoint:')} ${bdd.method('GET')} ${bdd.endpoint('/api/v1/legals')}
${bdd.label('• Access:')} ${bdd.access('Public (No Authentication Required)')}
${bdd.label('• Response Structure:')}
  - { success: true, statusCode: 200, message: "Legal pages retrieved successfully", data: Array<ILegalPage> }
`);

      await createLegalPageFixture({ title: 'Terms of Service' });
      await createLegalPageFixture({ title: 'Privacy Policy' });
      await createLegalPageFixture({ title: 'Refund Policy' });

      const response = await request(app)
        .get('/api/v1/legals')
        .expect(StatusCodes.OK);

      logApi(
        'GET',
        '/api/v1/legals',
        {},
        response.body,
        'BDD-02-GET-ALL-LEGALS',
        'Retrieve all legal pages',
      );

      assertSuccessResponse(response.body);
      expect(Array.isArray(response.body.data)).toBe(true);
      expect(response.body.data.length).toBe(3);
      expect(response.body.data[0]).toHaveProperty('title');
      expect(response.body.data[0].content).toBeUndefined();
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. GET SINGLE LEGAL PAGE BY ID
  // ═══════════════════════════════════════════════════════════════════════════
  describe('BDD-03 GET SINGLE LEGAL PAGE BY ID (Public / Lookup)', () => {
    it('BDD-03 public user retrieves legal page details by legalId', async () => {
      console.info(`
${bdd.header('📝 USER STORY:')}
As any Platform User or Visitor
I want to fetch full content of a specific legal policy using its legalId
So that I can read the complete terms or policy document

${bdd.section('📋 BUSINESS RULES & QUERY PAYLOAD SPECIFICATIONS:')}
${bdd.label('• Primary Endpoint:')} ${bdd.method('GET')} ${bdd.endpoint('/api/v1/legals/:legalId')}
${bdd.label('• Access:')} ${bdd.access('Public (No Authentication Required)')}
`);

      const legalPage = await createLegalPageFixture({
        title: 'Community Guidelines',
        content: '<p>Please treat all community members with respect.</p>',
      });

      const response = await request(app)
        .get(`/api/v1/legals/${legalPage._id}`)
        .expect(StatusCodes.OK);

      logApi(
        'GET',
        `/api/v1/legals/${legalPage._id}`,
        { params: { legalId: legalPage._id.toString() } },
        response.body,
        'BDD-03-GET-LEGAL-BY-ID',
        'Retrieve single legal page by legalId',
      );

      assertSuccessResponse(response.body);
      expect(response.body.data._id).toBe(legalPage._id.toString());
      expect(response.body.data.title).toBe('Community Guidelines');
      expect(response.body.data.content).toBe('<p>Please treat all community members with respect.</p>');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. UPDATE LEGAL PAGE
  // ═══════════════════════════════════════════════════════════════════════════
  describe('BDD-04 UPDATE LEGAL PAGE (Admin Operations)', () => {
    it('BDD-04-A admin updates title and content of an existing legal page', async () => {
      console.info(`
${bdd.header('📝 USER STORY:')}
As an Administrator
I want to modify the title or content of an existing legal page
So that platform policies stay updated with evolving business and legal requirements

${bdd.section('📋 BUSINESS RULES & QUERY PAYLOAD SPECIFICATIONS:')}
${bdd.label('• Primary Endpoint:')} ${bdd.method('PATCH')} ${bdd.endpoint('/api/v1/legals/:legalId')}
${bdd.label('• Access:')} ${bdd.access('ADMIN Only')}
`);

      const legalPage = await createLegalPageFixture({
        title: 'Initial Terms',
        content: '<p>Old initial content</p>',
      });

      const updatePayload = {
        title: 'Updated Terms of Service 2026',
        content: '<p>Updated and expanded legal terms content for 2026.</p>',
      };

      const response = await request(app)
        .patch(`/api/v1/legals/${legalPage._id}`)
        .set('Authorization', `Bearer ${adminAccessToken}`)
        .send(updatePayload)
        .expect(StatusCodes.OK);

      logApi(
        'PATCH',
        `/api/v1/legals/${legalPage._id}`,
        { params: { legalId: legalPage._id.toString() }, body: updatePayload },
        response.body,
        'BDD-04-UPDATE-LEGAL',
        'Admin updates legal page title and content',
      );

      assertSuccessResponse(response.body);
      expect(response.body.data.title).toBe(updatePayload.title);
      expect(response.body.data.content).toBe(updatePayload.content);

      const updated = await LegalPage.findById(legalPage._id);
      expect(updated?.title).toBe(updatePayload.title);
      expect(updated?.content).toBe(updatePayload.content);
    });

    it('BDD-04-B admin updates only the content of a legal page', async () => {
      const legalPage = await createLegalPageFixture({
        title: 'Cookie Policy',
        content: '<p>Basic cookies description</p>',
      });

      const updatePayload = {
        content: '<p>Comprehensive cookies and tracking technologies policy.</p>',
      };

      const response = await request(app)
        .patch(`/api/v1/legals/${legalPage._id}`)
        .set('Authorization', `Bearer ${adminAccessToken}`)
        .send(updatePayload)
        .expect(StatusCodes.OK);

      assertSuccessResponse(response.body);
      expect(response.body.data.title).toBe('Cookie Policy');
      expect(response.body.data.content).toBe(updatePayload.content);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. DELETE LEGAL PAGE
  // ═══════════════════════════════════════════════════════════════════════════
  describe('BDD-05 DELETE LEGAL PAGE (Admin Operations)', () => {
    it('BDD-05 admin successfully deletes an obsolete legal page', async () => {
      console.info(`
${bdd.header('📝 USER STORY:')}
As an Administrator
I want to delete an obsolete or deprecated legal page
So that users are not confused by outdated agreements

${bdd.section('📋 BUSINESS RULES & QUERY PAYLOAD SPECIFICATIONS:')}
${bdd.label('• Primary Endpoint:')} ${bdd.method('DELETE')} ${bdd.endpoint('/api/v1/legals/:legalId')}
${bdd.label('• Access:')} ${bdd.access('ADMIN Only')}
`);

      const legalPage = await createLegalPageFixture({
        title: 'Deprecated Beta Terms',
        content: '<p>Old beta testing terms</p>',
      });

      const response = await request(app)
        .delete(`/api/v1/legals/${legalPage._id}`)
        .set('Authorization', `Bearer ${adminAccessToken}`)
        .expect(StatusCodes.OK);

      logApi(
        'DELETE',
        `/api/v1/legals/${legalPage._id}`,
        { params: { legalId: legalPage._id.toString() } },
        response.body,
        'BDD-05-DELETE-LEGAL',
        'Admin deletes legal page',
      );

      assertSuccessResponse(response.body);

      const deleted = await LegalPage.findById(legalPage._id);
      expect(deleted).toBeNull();
    });
  });
});
