export enum ACCOUNT_STATE {
  UNVERIFIED = 'UNVERIFIED',
  VERIFIED = 'VERIFIED',
  LOCKED = 'LOCKED',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum APP_STATE {
  PENDING = 'PENDING',
  ACTION_REQUIRED = 'ACTION_REQUIRED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  REVOKED = 'REVOKED',
}

export enum VEHICLE_STATUS {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum DOCUMENT_STATUS {
  SCANNING_PENDING = 'SCANNING_PENDING',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum DOCUMENT_TYPE {
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  HACK_LICENSE = 'HACK_LICENSE',
  LOCAL_PERMIT = 'LOCAL_PERMIT',
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  VEHICLE_PHOTO = 'VEHICLE_PHOTO',
  VEHICLE_INSURANCE = 'VEHICLE_INSURANCE',
  VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
}

export enum SESSION_STATUS {
  ACTIVE = 'ACTIVE',
  REVOKED = 'REVOKED',
  INVALIDATED = 'INVALIDATED',
}

export enum USER_ROLES {
  ADMIN = 'ADMIN',
  PROMOTER = 'PROMOTER',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
}

export enum CARD_PAYMENT_STATUS {
  ACCEPTED = 'ACCEPTED',
  NOT_ACCEPTED = 'NOT_ACCEPTED',
}
